import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { BaseLayout } from '@/app/components';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={'dark'}>
    <body className={clsx(inter.className, 'h-svh w-full')}>
    <BaseLayout>
      {children}
    </BaseLayout>
    </body>
    </html>
  );
}
